In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.sample(10)

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
408878,408878,rural,3,0.32,25,night,foggy,False,True,morning,True,False,0,0.35
187590,187590,rural,2,0.86,60,night,clear,False,False,evening,False,True,3,0.81
267445,267445,urban,4,0.24,45,night,foggy,False,False,morning,False,False,2,0.43
284857,284857,rural,2,0.86,25,daylight,clear,False,True,evening,True,True,0,0.32
464936,464936,highway,2,0.40,45,dim,clear,False,False,afternoon,False,False,1,0.22
280890,280890,urban,4,0.10,60,dim,clear,True,False,afternoon,True,True,1,0.23
231392,231392,rural,1,0.06,45,night,rainy,False,True,morning,False,True,2,0.25
161947,161947,highway,3,0.59,25,dim,rainy,True,True,afternoon,True,True,2,0.29
123373,123373,highway,3,0.81,45,dim,foggy,True,False,evening,False,False,2,0.30
218155,218155,urban,4,0.53,35,night,clear,True,False,afternoon,False,True,3,0.39

In [4]:
df.shape

(517754, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517754 entries, 0 to 517753
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      517754 non-null  int64
 1   road_type               517754 non-null  object
 2   num_lanes               517754 non-null  int64
 3   curvature               517754 non-null  float64
 4   speed_limit             517754 non-null  int64
 5   lighting                517754 non-null  object
 6   weather                 517754 non-null  object
 7   road_signs_present      517754 non-null  bool
 8   public_road             517754 non-null  bool
 9   time_of_day             517754 non-null  object
 10  holiday                 517754 non-null  bool
 11  school_season           517754 non-null  bool
 12  num_reported_accidents  517754 non-null  int64
 13  accident_risk           517754 non-null  float64
dtypes: bool(4), float64(2), int64(4), object(4)
memory usage: 41.5+ MB

### road_type, num_lanes equally distrubuted

In [6]:
df["num_lanes"].value_counts()

num_lanes
1    131168
2    130054
4    129118
3    127414
Name: count, dtype: int64

In [7]:
df["lighting"].value_counts()

lighting
dim         183826
daylight    178015
night       155913
Name: count, dtype: int64

In [8]:
df["weather"].value_counts()

weather
foggy    181463
clear    179306
rainy    156985
Name: count, dtype: int64

In [9]:
df.drop(columns=["id"],inplace=True)

In [10]:
x_train, x_test,y_train, y_test = train_test_split(df.drop(columns=["accident_risk"]),df["accident_risk"],test_size=0.3)

In [11]:
bool_cols = x_train.select_dtypes(include='bool')


for col in bool_cols:
    x_train[col] = x_train[col].astype(int)
    x_test[col] = x_test[col].astype(int)

In [12]:
x_train

,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents
459656,rural,3,0.85,70,dim,foggy,1,0,afternoon,0,0,2
156571,rural,2,0.28,60,daylight,rainy,0,0,morning,1,1,1
44786,urban,2,0.15,45,night,rainy,1,1,morning,1,1,1
321075,highway,2,0.37,25,night,clear,0,0,afternoon,1,0,2
62161,highway,1,0.73,45,dim,rainy,1,1,morning,0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...
264294,urban,3,0.57,45,night,rainy,0,1,evening,1,1,3
339999,highway,4,0.57,25,dim,foggy,1,0,afternoon,0,0,2
155640,highway,2,0.75,60,night,foggy,0,1,afternoon,1,1,3
66330,highway,4,0.72,45,night,rainy,0,1,morning,1,1,0
222212,rural,3,0.04,45,night,foggy,1,0,afternoon,1,0,2

In [13]:
obj_col = x_train.select_dtypes(include="object").columns

obj_col

Index(['road_type', 'lighting', 'weather', 'time_of_day'], dtype='object')

In [14]:
for col in obj_col:
    print(y_train.groupby(x_train[col]).mean())

road_type
highway    0.349884
rural      0.349945
urban      0.357136
Name: accident_risk, dtype: float64
lighting
daylight    0.302815
dim         0.300145
night       0.470450
Name: accident_risk, dtype: float64
weather
clear    0.309806
foggy    0.386287
rainy    0.361523
Name: accident_risk, dtype: float64
time_of_day
afternoon    0.351291
evening      0.354750
morning      0.350878
Name: accident_risk, dtype: float64

as all the categorical colm will be onehotencoded able

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
ohe=OneHotEncoder(sparse_output=False,drop='first')

In [33]:
x_train_encoded=ohe.fit_transform(x_train[obj_col])
x_test_encoded=ohe.fit_transform(x_test[obj_col])

In [22]:
x_train_encoded

array([[0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]], shape=(517754, 8))

In [ ]:
x_train_other=x_train.select_dtypes(include=["int","float"])
x_test_other=x_test.select_dtypes(include=["int","float"])

(362427, 8)

In [48]:
x_train_other.values

array([[3.0e+00, 8.5e-01, 7.0e+01, ..., 0.0e+00, 0.0e+00, 2.0e+00],
       [2.0e+00, 2.8e-01, 6.0e+01, ..., 1.0e+00, 1.0e+00, 1.0e+00],
       [2.0e+00, 1.5e-01, 4.5e+01, ..., 1.0e+00, 1.0e+00, 1.0e+00],
       ...,
       [2.0e+00, 7.5e-01, 6.0e+01, ..., 1.0e+00, 1.0e+00, 3.0e+00],
       [4.0e+00, 7.2e-01, 4.5e+01, ..., 1.0e+00, 1.0e+00, 0.0e+00],
       [3.0e+00, 4.0e-02, 4.5e+01, ..., 1.0e+00, 0.0e+00, 2.0e+00]],
      shape=(362427, 8))

In [42]:
x_test_rest=x_test_other.values
x_train_rest=x_train_other.values
x_train_rest

array([[3.0e+00, 8.5e-01, 7.0e+01, ..., 0.0e+00, 0.0e+00, 2.0e+00],
       [2.0e+00, 2.8e-01, 6.0e+01, ..., 1.0e+00, 1.0e+00, 1.0e+00],
       [2.0e+00, 1.5e-01, 4.5e+01, ..., 1.0e+00, 1.0e+00, 1.0e+00],
       ...,
       [2.0e+00, 7.5e-01, 6.0e+01, ..., 1.0e+00, 1.0e+00, 3.0e+00],
       [4.0e+00, 7.2e-01, 4.5e+01, ..., 1.0e+00, 1.0e+00, 0.0e+00],
       [3.0e+00, 4.0e-02, 4.5e+01, ..., 1.0e+00, 0.0e+00, 2.0e+00]],
      shape=(362427, 8))

In [36]:
x_train_encoded

array([[1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 1., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.]], shape=(362427, 8))

In [51]:
final_train = np.hstack([x_train_rest, x_train_encoded])
final_test = np.hstack([x_test_rest, x_test_encoded])

(array([[1., 0., 1., ..., 0., 0., 0.],
        [1., 0., 0., ..., 1., 0., 1.],
        [0., 1., 0., ..., 1., 0., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 1.],
        [1., 0., 0., ..., 0., 0., 0.]], shape=(362427, 8)),
 array([[3.0e+00, 8.5e-01, 7.0e+01, ..., 0.0e+00, 0.0e+00, 2.0e+00],
        [2.0e+00, 2.8e-01, 6.0e+01, ..., 1.0e+00, 1.0e+00, 1.0e+00],
        [2.0e+00, 1.5e-01, 4.5e+01, ..., 1.0e+00, 1.0e+00, 1.0e+00],
        ...,
        [2.0e+00, 7.5e-01, 6.0e+01, ..., 1.0e+00, 1.0e+00, 3.0e+00],
        [4.0e+00, 7.2e-01, 4.5e+01, ..., 1.0e+00, 1.0e+00, 0.0e+00],
        [3.0e+00, 4.0e-02, 4.5e+01, ..., 1.0e+00, 0.0e+00, 2.0e+00]],
       shape=(362427, 8)))

In [50]:
final_train

array([[3.0e+00, 8.5e-01, 7.0e+01, ..., 0.0e+00, 0.0e+00, 0.0e+00],
       [2.0e+00, 2.8e-01, 6.0e+01, ..., 1.0e+00, 0.0e+00, 1.0e+00],
       [2.0e+00, 1.5e-01, 4.5e+01, ..., 1.0e+00, 0.0e+00, 1.0e+00],
       ...,
       [2.0e+00, 7.5e-01, 6.0e+01, ..., 0.0e+00, 0.0e+00, 0.0e+00],
       [4.0e+00, 7.2e-01, 4.5e+01, ..., 1.0e+00, 0.0e+00, 1.0e+00],
       [3.0e+00, 4.0e-02, 4.5e+01, ..., 0.0e+00, 0.0e+00, 0.0e+00]],
      shape=(362427, 16))

In [52]:
from sklearn.tree import DecisionTreeRegressor

In [53]:
model=DecisionTreeRegressor()

model.fit(final_train,y_train)

DecisionTreeRegressor()

In [55]:
y_pred=model.predict(final_test)

In [56]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred,y_test)

0.006909620724879341