In [34]:
import pandas as pd
import numpy as np

In [35]:
credits=pd.read_csv("tmdb_5000_credits.csv")
movies=pd.read_csv("tmdb_5000_movies.csv")

In [36]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [37]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [38]:
movies=movies.merge(credits, on="title")

In [39]:
movies.shape

(4809, 23)

In [40]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

#### now we will romove the column that are not required to us 
basically we are going to make a cloumns name tag that will contain the info about the moive that help us to recommend movie

## 📂 Required Columns / Features

For this project, we are using the following columns from the TMDB 5000 dataset:

- **genres** → Helps categorize the movie (e.g., Action, Comedy, Drama).  
- **id** → Unique identifier for each movie; also useful for fetching posters.  
- **keywords** → Tags related to the movie, useful for content similarity.  
- **title** → The movie title.  
- **overview** → Summary of the movie; movies with similar overviews are likely similar in content.  
- **cast** → Main actors in the movie.  
- **crew** → Key crew members (like director) who influence the movie’s style/theme.

In [41]:
movies = movies[["genres", "id", "keywords", "title", "overview", "cast", "crew"]]

In [42]:
movies.head(2)

,genres,id,keywords,title,overview,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [43]:
movies.isnull().sum()

genres      0
id          0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [44]:
movies.dropna(inplace=True)

In [45]:
movies.duplicated().sum()

np.int64(0)

In [46]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [47]:
import ast
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i["name"])
    return l

In [48]:
movies["genres"]= movies["genres"].apply(convert)

In [49]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [50]:
movies.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [51]:
movies["keywords"] = movies["keywords"].apply(convert)

In [52]:
movies.iloc[0].cast

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [53]:

def convert3(obj):
    l=[]
    conter=0
    for i in ast.literal_eval(obj):
        if conter !=3:
            l.append(i["name"])
            conter+=1
        else:
            break
    return l

movies["cast"] = movies["cast"].apply(convert3)

In [54]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [55]:
movies["crew"][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [56]:
def fetch_director(obj):
    l=[]
    conter=0
    for i in ast.literal_eval(obj):
        if i["job"]=="Director":
            l.append(i["name"])
            break
    return l

In [57]:
movies["crew"] = movies["crew"].apply(fetch_director)

In [58]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [59]:
movies["genres"]=movies["genres"].apply(lambda x: [i.replace(" ","") for i in x])
movies["keywords"]=movies["keywords"].apply(lambda x: [i.replace(" ","") for i in x])
movies["cast"]=movies["cast"].apply(lambda x: [i.replace(" ","") for i in x])
movies["crew"]=movies["crew"].apply(lambda x: [i.replace(" ","") for i in x])

In [60]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,A cryptic message from Bond’s past sends him o...,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"John Carter is a war-weary, former military ca...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [61]:
movies["tags"]= movies["genres"]+movies["keywords"]+movies["cast"]+movies["crew"]

In [62]:
movies=movies[["id", "title","tags"]]

In [63]:
movies.head()

,id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."

In [64]:
movies["tags"]=movies["tags"].apply(lambda x: " ".join(x))

In [70]:
movies.head()

,id,title,tags
0,19995,Avatar,action adventure fantasy sciencefiction cultur...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...
2,206647,Spectre,action adventure crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,action crime drama thriller dccomics crimefigh...
4,49529,John Carter,action adventure sciencefiction basedonnovel m...

In [68]:
movies["tags"] =movies["tags"].apply(lambda x:x.lower())

In [88]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words="english")

In [89]:
vectors = cv.fit_transform(movies["tags"]).toarray()

In [90]:
for i in cv.get_feature_names_out():
    print(i)

16thcenturi
17thcenturi
18thcenturi
1910
1930
1940
1950
1960
1970
1980
1990
19thcenturi
21stcenturi
3d
aaroneckhart
aarontaylor
abbiecornish
abhishekbachchan
abigailbreslin
aborigin
abram
absurd
abus
abusivehusband
accid
action
actionhero
activist
actor
actress
adambeach
adambrodi
adamcarolla
adamdriv
adamgarcia
adamgoldberg
adammckay
adamrifkin
adamsandl
adamscott
adamshankman
adapt
addict
adolesc
adolfhitl
adopt
adoptedchild
adoptivefath
adrianlyn
adrienbrodi
adriennebarbeau
adultanim
adulteri
advanc
adventur
adversari
advertisingexecut
advertisingexpert
advic
affair
affect
afghanistan
africa
africanamerican
aftercreditssting
afterlif
age
agediffer
agent
aggressionbyanim
aid
aidanquinn
aimeegarcia
airforc
airplan
airplanecrash
airport
akshaykumar
alanalda
alanarkin
alanpark
alanrickman
alantudyk
alaska
albertbrook
albertfinney
alberthugh
alcatraz
alcohol
alcoholabus
alecbaldwin
alecguin
alejandroamenábar
alejandrogonzáleziñárritu
alessandronivola
alexanderpayn
alexanderskarsgård
alexandradaddario
alexandreaja
alexapenavega
alexisbledel
alexkendrick
alexpettyf
alexproya
alfonsocuarón
alfredhitchcock
alfredmolina
alfrewoodard
alicebraga
aliceev
aliciasilverston
aliciavikand
aliciawitt
alien
alienabduct
alienattack
aliencontact
alieninfect
alieninvas
alienlife
alienphenomenon
alienplanet
alilart
alisonlohman
alli
allig
alon
alp
alpacino
alterego
alternatedimens
alternatehistori
alternater
alternativer
alysonhannigan
alzheim
alzheimer
amandabyn
amandapeet
amandaseyfri
amazon
ambassador
amberheard
ambertamblyn
ambit
ambul
ambush
americaferrera
american
americanabroad
americancivilwar
americandream
americanflag
americanfootbal
americanfootballplay
amnesia
amsterdam
amusementpark
amyadam
amyheckerl
amypoehl
amyryan
amysmart
anaclaudiatalancón
anandtuck
anarchiccomedi
ancientchina
ancientegypt
ancientgreec
ancientrom
ancientworld
anderson
andiemacdowel
andrebraugh
andrewadamson
andrewbujalski
andrewdavi
andrewflem
andrewgarfield
andrewniccol
andrewstanton
android
andrzejbartkowiak
andyfickman
andygarcía
andylau
andysamberg
andyserki
andytenn
angel
angelabassett
angelinajoli
anger
angle
anim
animalattack
animalhorror
animallead
animalprotect
animalsidekick
anjelicahuston
annabellasciorra
annafari
annafriel
annakendrick
annapaquin
annasophiarobb
annearch
annebancroft
annefletch
annehathaway
annehech
annemoss
annetteben
anonym
anonymouslett
anotherdimens
ant
antarct
antarctica
antholog
anthonyanderson
anthonyhopkin
anthonymacki
anthonyminghella
anthonyquinn
anthonyrusso
anthropomorph
anti
antihero
antisemit
antiterror
antoinefuqua
antoncorbijn
antoniobandera
antonyelchin
apart
apartheid
ape
apocalyps
apocalypt
apostl
apprentic
aquarium
arab
arbitrarylaw
archaeologist
archeolog
archer
archeri
architect
arci
arctic
area51
arena
argument
aristocrat
arizona
armandassant
armi
armiehamm
arminmueller
armoredcar
armsdeal
arnoldschwarzenegg
arrangedmarriag
arrest
arrog
arson
art
artgalleri
arthous
artifact
artificialinsemin
artificialintellig
artist
arttheft
artthief
asabutterfield
ashleyjudd
ashleytisdal
ashtonkutch
asia
aspiringsing
assassin
assassinationattempt
assault
assaultrifl
assign
assist
asteroid
astronaut
asylum
atheist
athlet
atlanticocean
atomegoyan
atomicbomb
attack
attemptedmurd
attemptedrap
attempttoescap
attic
attract
auction
audiotap
audit
audreyhepburn
audreytaut
aunt
auntniecerelationship
australia
australianoutback
austria
author
autism
auto
automobilerac
autoritianeduc
awkward
ax
babi
baby
babysitt
bachelor
backpack
badboss
badluck
badmother
bagoverhead
bahama
ball
ballet
balloon
baltasarkormákur
baltimoremaryland
bammargera
band
bangkok
bank
banker
bankrobb
bankrobberi
bar
barbarahershey
barbarian
barbrastreisand
barcelonaspain
barfight
barn
barrylevinson
barrypepp
barrysonnenfeld
barsandrestaur
basebal
baseballbat
basedonarticl
basedoncartoon
basedonchildren
basedoncomicbook
basedoncomicstrip
basedonfairytal
basedonfilm
basedongraphicnovel
basedonnovel
basedonplay
basedonshortstori
basedonstagemus
basedontrueev
basedontruestori
basedontvseri
basedonvideogam
basedonyoungadultnovel
basement
basketbal
bat
bath
bathroomhumor
bathtub
batman
battl
battleassign
battlefield
battleforpow
bazluhrmann
bdsm
beach
beachhous
bear
beard
beast
beat
beauti
beautifulwoman
beautycontest
becominganadult
bedroom
beer
beguil
behead
belgium
benaffleck
benbarn
benchaplin
benedictcumberbatch
benfost
bengazzara
beniciodeltoro
benitomussolini
benjaminbratt
benkingsley
bennofürmann
benstil
benwhishaw
berlin
berniemac
bestfriend
bestfriendsinlov
bet
betray
bettemidl
bettythoma
beverlyhil
beyoncéknowl
bia
bibl
bigfamili
biker
bikini
billard
billbellami
billcondon
billewoodruff
billhad
billionair
billmoseley
billmurray
billnighi
billpaxton
billpullman
billybobthornton
billyburk
billyconnolli
billycrudup
billycryst
billythekid
billywild
billyzan
binocular
biographi
biolog
biologicalweapon
bird
birth
birthday
bisexu
bite
bittersweet
blackandwhit
blackhol
blackhumor
blackmag
blackmail
blackmen
blackout
blackpeopl
blacksmith
blade
blakel
blast
blaxploit
blind
blinddat
blindnessandimpairedvis
blizzard
blog
blond
blood
bloodsplatt
blowjob
blue
boardingschool
boat
boatchas
boazyakin
bobbyfarrelli
bobclark
bobgunton
bobhoskin
bobodenkirk
body
bodyexchang
bodyguard
bodyhorror
bokeemwoodbin
bollywood
bomb
bomber
bondag
bongjoon
bonniehunt
boobytrap
book
bookstor
boredom
boss
boston
botanist
bounti
bountyhunt
bourgeoisi
bowandarrow
bowl
box
boxer
boxingmatch
boy
boyfriend
boyfriendex
boyfriendgirlfriendrelationship
boygeniu
boys
bradanderson
bradbird
braddourif
bradfurman
bradleycoop
bradpeyton
bradpitt
bradsilberl
bradycorbet
brain
braintumor
brainwash
brandont
braveri
brawl
brazil
brazilian
break
breakdanc
breakingthefourthwal
breast
breckeisn
breckinmey
brendanfras
brendangleeson
brentonthwait
brentspin
brettratn
briancox
briandennehi
briandepalma
brianhelgeland
brianlev
brianrobbin
briantaylor
briantrenchard
bride
bridegroom
bridesmaid
bridg
bridgetfonda
brielarson
brien
britain
british
britisharmi
britishempir
britishsecretservic
britmarl
brittanymurphi
brittanysnow
brittrobertson
broadway
brokenengag
brokenneck
broker
bronx
brook
brookeshield
brooklynnewyorkc
broom
brothel
brother
brotherbrotherrelationship
brothersisterrelationship
bruceberesford
brucecampbel
brucedern
brucegreenwood
brucewilli
brutal
bryancranston
bryansing
brycedallashoward
bu
budapest
buddhism
buddhistmonk
buddi
buddycomedi
buddycop
bulletwound
bulli
bunker
bunni
bureaucraci
burglar
buriedal
burnedal
burrsteer
burtlancast
burtreynold
bush
busi
businessman
businessstart
busrid
butler
bythewood
cabin
cabininthewood
cage
cairo
california
callgirl
cambodia
camcord
cameronbright
cameroncrow
camerondiaz
camgigandet
camillabel
camp
campaign
campbellscott
campu
canada
cancer
candi
candlelightvigil
cannabi
cannib
cano
canuxploit
caper
capit
captain
captiv
captur
car
caraccid
carbomb
carchas
carcrash
cardeal
cardgam
career
careerwoman
caretak
carexplos
careymulligan
cargoship
caribbean
caricevanhouten
carjack
carjourney
carlagugino
carlfranklin
carlossaldanha
carlyschroed
carmenejogo
carniv
carpet
carrac
carrie
carriefish
carsetonfir
cartoon
caruso
caryelw
caseyaffleck
casino
castl
castrat
cat
cataclysm
catandmous
catastroph
cateblanchett
catherinedeneuv
catherinehardwick
catherinekeen
catherinemccormack
catherineo
catherinezeta
cathol
catholic
catholicchurch
catholicpriest
cattledr
cavalri
cave
cavemen
cedrictheentertain
celebr
cello
cellphon
cemeteri
centralandsouthamerica
centralpark
ceremoni
cgi
chadmichaelmurray
chain
chainsaw
championship
chanc
chandor
chang
changingthepastorfutur
channingtatum
chao
chariti
charlesd
charlesferguson
charlesherman
charlesmartinsmith
charless
charliecox
charlieday
charliehunnam
charliesheen
charlietahan
charlizetheron
charlotterampl
charltonheston
chase
chasesandrac
chauffeur
chazzpalminteri
cheat
cheatingwif
cheerlead
chef
chemic
cher
chevychas
chicago
chicken
chief
child
childabus
childhero
childhoodfriend
childhoodmemori
childhoodtrauma
childlabour
childmurder
childprodigi
children
chimcbrid
chimp
chimpanze
china
chinatown
chipmunk
chiwetelejiofor
chloëgracemoretz
chloësevigni
chocol
choimin
choir
cholo
chosenon
chowyun
chriscolumbu
chriscoop
chrisevan
chrishemsworth
chriskattan
chrisklein
chrismil
chrisnoth
chriso
chrispin
chrispratt
chrisrock
chrissand
christ
christian
christianbal
christianclavi
christianfilm
christianslat
christinaappleg
christinaricci
christma
christmascarol
christmasev
christmasparti
christmastre
christophereccleston
christopherguest
christopherlambert
christopherlloyd
christophermcdonald
christophermcquarri
christophermintz
christophernolan
christopherplumm
christopherreev
christopherwalken
christophwaltz
christuck
chriswedg
chrisweitz
chu
chuckrussel
church
churchchoir
churchservic
cia
ciaagent
ciaránhind
cigarettesmok
cigarsmok
cillianmurphi
cinderella
cinema
circu
citi
cityruin
civilright
civilwar
clairedan
claireforlani
clancybrown
clarkgabl
class
classdiffer
classicalmus
classmat
classprejudic
classroom
classsocieti
claudevandamm
claustrophobia
cleaduval
clerk
cliff
cliffcurti
climat
climatechang
climb
clinteastwood
cliveowen
clock
clocktow
clone
clown
club
clumsyfellow
coach
coalmin
coastguard
cocain
cockneyacc
cockroach
code
coffin
cohabit
cohen
coldwar
colehaus
colinfarrel
colinfirth
collector
colleg
collegestud
colmfeor
colmmeaney
colombia
colonel
coloni
colorado
coma
combat
comeback
comedi
comedian
comet
comicbook
comingofag
comingout
command
commando
commerci
common
commun
compani
compass
competit
compos
compulsivegambl
comput
computerhack
computerprogram
computerviru
conartist
concentrationcamp
concert
concili
condom
confederatesoldi
confess
confid
congress
conman
connel
connienielsen
connor
conradvernon
conserv
conspiraci
conspiracyofmurd
conspiracytheori
contest
contractkil
control
conveniencestor
convert
convict
convoy
cook
cop
corbinbernsen
coreyfeldman
coron
corpor
corps
corrupt
corruptcop
cosmato
costasmandylor
costum
countdown
countryhous
countrylif
countrymus
countrysid
coupd
courag
court
courtcas
courteneycox
courthous
courtroom
cover
coveredinvestig
cow
cowardic
cowardli
cowboy
crab
craigbierko
craiggillespi
craigt
crash
creatur
cri
crime
crimefamili
crimefight
crimin
criminalmastermind
crisi
crispinglov
crocodil
crookedlawy
cross
crossdress
crucifix
crucifixion
cruelti
cruis
crusad
crush
cryogen
cuba
cubagoodingjr
cult
cultclass
cultfavorit
cultfilm
cultur
cultureclash
cure
curios
curs
curtishanson
custodybattl
cut
cuttingthecord
cyberpunk
cyborg
cynic
daili
dailylif
dakotafan
danaykroyd
danc
dancer
danceteach
dancingmast
dancingscen
danecook
danedehaan
danfogl
danfutterman
danger
danielbrühl
danielcraig
danielday
danielespinosa
danielleharri
danielradcliff
danielstern
dannyaiello
dannyboyl
dannydevito
dannydy
dannyglov
dannyhuston
dannymcbrid
dannytrejo
danyboon
dark
darkcomedi
darkfantasi
darkhero
darkpast
darksecret
darrenaronofski
darrenlynnbousman
darylhannah
darylsabara
date
daughter
davechappel
davefranco
davi
davidarquett
daviday
davidbow
davidcarradin
davidcaruso
davidcronenberg
davidcross
daviddobkin
davidduchovni
davidfinch
davidfrankel
davidgordongreen
davidhand
davidhewlett
davidhydepierc
davidkeith
davidkelli
davidkoepp
davidlean
davidlynch
davidmorrissey
davidmors
davido
davidoyelowo
davidr
davids
davidschwimm
davidslad
davidspad
davidstrathairn
davidthewli
davidtwohi
davidwain
davidwarn
davidy
davidzuck
davisguggenheim
daxshepard
daydream
dccomic
dcextendedunivers
dea
deaagent
deadbodi
deadli
deadpar
deaf
deal
dean
deanparisot
death
deathbyaccid
deathofachild
deathofafriend
deathoffath
deathofhusband
deathoflov
deathofwif
deathpenalti
deathrow
deathstar
deborahkaraung
debt
decapit
deceivedhusband
deceivedwif
decept
decis
deepikapadukon
deepsea
deer
defens
deforestkelley
dejavu
delinqu
delirium
delorean
delroylindo
delus
dementia
demimoor
demiánbichir
demon
demonicpossess
denholmelliott
deniserichard
denisleari
denisvilleneuv
denmark
denniegordon
dennisdugan
dennishopp
dennisquaid
dentist
denunci
denzelwashington
departmentstor
deport
depress
derekjacobi
derekluk
dermotmulroney
desert
desertedisland
desir
despair
desper
destini
destroy
destruct
detect
detroit
detroitmichigan
devil
devonsawa
devpatel
dialogu
diamant
diamond
dianekeaton
dianekrug
dianelan
diannewiest
diari
dictat
die
diet
difficultchildhood
diner
dinosaur
dirtycop
disabl
disappear
disast
disasterfilm
disastermovi
discjockey
disco
discoveri
diseas
disembowel
disfigur
disfiguredfac
disguis
disgust
dishonesti
dismember
disord
districtattorney
distrust
dive
divorc
djimonhouns
djpooh
dna
doctor
document
documentari
documentaryfilmmak
dog
dogfight
doll
dollar
dolphin
dolphlundgren
domdeluis
domesticviol
domhnallgleeson
dominatrix
dominiccoop
dominicpurcel
dominicsena
dominicwest
donaldfaison
donaldpetri
donaldpleas
donaldsutherland
doncheadl
doncoscarelli
donmichaelpaul
donnel
donnieyen
donut
doomsday
doppelgang
dormitori
doublecross
doublelif
douglasmcgrath
dougliman
dougrayscott
dove
downsiz
dracula
drag
dragon
drakebel
drama
dream
dreamsequ
drewbarrymor
drifter
drink
driver
drown
drug
drugabus
drugaddict
drugcartel
drugcrim
drugdeal
drughumor
druglord
drugmul
drugsmuggl
drugtraff
drugus
drunk
dualident
dublin
dude
duel
duke
duncanjon
duringcreditssting
dustinhoffman
dutton
dwarv
dwaynejohnson
dwightyoakam
dyinganddeath
dylanbak
dylanmcdermott
dysfunct
dysfunctionalfamili
dysfunctionalmarriag
dystopia
dystopicfutur
earth
earthquak
easterneurop
eastindiatradingcompani
eccentr
eclips
econom
ecstasi
eddiegriffin
eddiemurphi
eddieredmayn
edgarramírez
edgarwright
edharri
edhelm
editor
edspel
educ
edwardburn
edwardfurlong
edwardherrmann
edwardnorton
edwardzwick
egg
egypt
elderli
elect
electioncampaign
electricchair
electricshock
eleph
elev
eliakazan
eliaskotea
elijahwood
eliroth
elisabethshu
elishacuthbert
elizabethbank
elizabethhurley
elizabethperkin
elizabethpeña
elizadushku
ellefan
ellenbarkin
ellenburstyn
ellenpag
elli
elv
embassi
embethdavidtz
embezzl
emigr
emilehirsch
emilioestevez
emilyblunt
emilybrown
emilymortim
emilywatson
emmanuellechriqui
emmarobert
emmaston
emmathompson
emmawatson
emperor
employe
employeremployeerelationship
empower
enchant
endoftheworld
enemi
energysuppli
engag
engin
england
ensemblecast
entrap
envi
environment
epic
epidem
epilepsi
ericbana
ericdarnel
ericmabiu
ericrobert
ernestborgnin
erotic
eroticmovi
esaimoral
escap
escapad
escapedconvict
escapefromprison
espionag
essenceatkin
estat
estateag
etat
ethanembri
ethanhawk
ethic
ethnicstereotyp
eugenelevi
eugenioderbez
europ
euthanasia
evacu
evagreen
evalongoria
evamend
evanrachelwood
everettmcgil
evid
evil
evilcorpor
evildol
evilmoth
evilspirit
evilstepmoth
evilwitch
evolut
ewanmcgregor
ex
execut
exercis
exhibit
exhusband
existenti
exorc
exoticisland
expedit
expensiverestaur
experi
explodingbuild
explodinghous
exploit
explos
exsoldi
extort
extramaritalaffair
extraterrestri
extraterrestrialtechnolog
extremeviol
eye
ezramil
factori
factorywork
fairi
fairuzabalk
fairy
fairytal
faith
fakedocumentari
fakeident
falcon
fall
fallinginlov
falsehistori
falseident
falselyaccus
fame
famili
family
familyclan
familyconflict
familyfeud
familyholiday
familyrelationship
familyreunion
familysecret
familyvac
famin
famkejanssen
famousscor
fanat
fangvamp
fantasi
fantasyworld
farewel
farm
farmer
farmhous
farmwork
fascism
fashion
fashiondesign
fashionmodel
fat
fate
father
fatherdaughterrelationship
fatherfigur
fatherhood
fathermurd
fathersonconflict
fathersonrelationship
fayedunaway
fbi
fbiagent
fear
feder
feel
felicityhuffman
felicityjon
female
femaleassassin
femalecorps
femalefriendship
femalenud
femaleprotagonist
femalevampir
femmefatal
feralchild
fernandomeirel
fetish
fiancé
fictionalgovernmentag
fictionalplac
fictionalwar
fictitiousmarriag
fight
fighter
fighterpilot
filmbusi
filmdirector
filmedkil
filmindustri
filmmak
filmnoir
filmproduc
financ
financialcrisi
financialtransact
fingerprint
firearm
fireengin
firemen
firework
firstlov
firsttim
fish
fisherman
fishoutofwat
fistfight
flamethrow
flashback
flat
fli
flight
flirt
flood
florida
floridakey
florist
flower
flowershop
flyingcar
flyingsauc
fog
folkhero
food
fool
footchas
forbiddenlov
forcefield
foreign
forest
forestwhitak
forgiv
form
fort
fortunetel
fosterpar
foundfootag
fox
frame
framedformurd
franc
francesmcdormand
franceso
francisfordcoppola
francislawr
frankapotent
frankcapra
frankcoraci
frankdarabont
frankenstein
frankgrillo
frankiemuniz
franklangella
franklinj
frankmarshal
frankoz
françoiscluzet
fratern
fraternityhous
fraud
freak
freddiehighmor
freddieprinzejr
fredward
fredzinnemann
freedom
freedomfight
freelov
freez
freidapinto
french
frenchrevolut
friend
friendship
frog
fromragstorich
fugit
fulfillingpropheci
funer
funeralhom
futur
futurewar
futurist
fword
gabrielbyrn
gabrielemuccino
gabrielmacht
gaelgarcíabern
galaxi
galleri
gallow
gambl
gambler
gamblingdebt
game
gameshow
gang
gangmemb
gangrap
gangster
gangsterboss
gangwar
garag
garbag
garden
garretthedlund
garrymarshal
garyfled
garygray
garyoldman
garyross
garysinis
garywinick
gasstat
gavinhood
gavino
gay
gayinterest
gayleadcharact
gayman
gayrelationship
geenadavi
gemmaarterton
genarowland
genehackman
gener
generationsconfilct
genet
geneticengin
genewild
geniu
genndytartakovski
genocid
genocideinrwanda
geoffreyrush
georgea
georgecarlin
georgeclooney
georgekennedi
georgeluca
georgemil
georgep
georgesidney
georgetillman
georgew
gerardbutl
germani
germanshepherd
ghetto
ghost
ghostship
ghosttown
ghostworld
giant
giantmonst
giantrobot
giantsnak
giantwav
gift
gilliananderson
ginaprince
giovanniribisi
girl
girlfriend
girlfriendrelationship
gladiat
glennclos
glennficarra
globalwarm
gnostic
goblin
god
godzilla
gold
goldengatebridg
goldengun
goldiehawn
golf
gondola
gongli
goodandbad
goodend
goodvsevil
gore
goreverbinski
gorilla
gossip
gothamc
gothic
govern
governor
gr
graduat
grandfathergranddaughterrelationship
grandfathergrandsonrelationship
grandmothergranddaughterrelationship
grave
greatbritain
greatdepress
greatwhiteshark
greec
greed
greekmytholog
green
gregghenri
gregkinnear
gregmottola
gregoryhoblit
gregorypeck
gretagerwig
gretchenmol
grief
griev
griffindunn
grizzlybear
grocerystor
grossoutcomedi
groupi
groupoffriend
growingup
guantanamobay
guard
guerrilla
guillaumecanet
guillermodeltoro
guilt
guitar
gulfwar
gun
gunbattl
gunfight
guninmouth
gunrampag
gunsling
gunviol
gurinderchadha
guru
gusvans
guyhamilton
guypearc
guyritchi
gwynethpaltrow
gym
gymnasium
gypsi
gérarddepardieu
hack
hacker
hade
haileesteinfeld
hairdress
hairloss
hal
haleybennett
haleyjoelos
half
halfbre
halfsist
halleberri
halloran
halloween
hallucin
hamburggermani
hammer
hammerhorror
hamster
handcuff
handgrenad
handtohandcombat
hang
hangov
hankazaria
hara
harass
haroldbeck
haroldrami
harrisonford
harryconnickjr
harrylloyd
harvardunivers
harveykeitel
hatr
haunt
hauntedhous
hav
havingfun
hawaii
hayaomiyazaki
haydenchristensen
haydenpanettier
hayleyatwel
haze
hazmatsuit
headinjuri
headlin
heal
health
hear
heart
heartattack
heartbreak
heartdiseas
heat
heathergraham
heatherlangenkamp
heatherlocklear
heathermatarazzo
heathledg
heaven
heavymet
heavyrain
hebrew
heikemakatsch
heir
heiress
heirtothethron
heist
heistmovi
heldatgunpoint
heldcapt
helenabonhamcart
helenhunt
helenmirren
helicopt
hell
henrycavil
henryfonda
henryjoost
henrythoma
henson
hero
heroicmiss
heroin
heroism
heterosexu
hiddencamera
hiddenident
hide
hidingplac
highschool
highschoolreunion
highschoolsport
highschoolstud
highsocieti
highway
hijack
hijackingoftrain
hike
hil
hilaryduff
hilaryswank
himalaya
hindu
hinduism
hip
hippi
hiroyukisanada
histori
historicalfigur
hitandrun
hitbyacar
hitchcockian
hitchhik
hitman
hiv
ho
hobbit
hold
holiday
hollyhunt
hollywood
holocaust
hologram
holygrail
holywat
home
homeinvas
homeland
homeless
homelessperson
homesick
homicid
homicidedetect
homophobia
homosexu
honeymoon
hongkong
honor
hood
hoodlum
hop
hope
hopedavi
horror
horrorspoof
hors
horsebackrid
horserac
hospit
hostag
hostage
hostagedrama
hostagesitu
hostil
hotel
hotelroom
hottub
hous
housekeep
housewif
howarddeutch
hrithikroshan
hughdanc

In [83]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [85]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [87]:
movies["tags"]=movies["tags"].apply(stem)

In [91]:
from sklearn.metrics.pairwise import cosine_similarity

In [104]:
similarity =cosine_similarity(vectors)

In [105]:
sorted(list(enumerate(similarity[0])),reverse=True,key= lambda x:x[1])[1:6]

[(47, np.float64(0.3849001794597506)),
 (2374, np.float64(0.3442651863295482)),
 (61, np.float64(0.33333333333333337)),
 (83, np.float64(0.3142696805273545)),
 (2405, np.float64(0.3012320380383547))]

In [119]:
def recommend_movie(choice):
    movie_index = movies[movies["title"]== choice].index[0]
    distances = similarity[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True,key= lambda x:x[1])[1:6]

    for i in movie_list:
        print(movies.iloc[i[0]].title)
    return

In [124]:
recommend_movie("Batman")

Batman
Batman & Robin
Batman Returns
Batman
Batman v Superman: Dawn of Justice